### PR TITLE
[FIX]

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/test/pull/11).

**Comment by nicomacr** [comment]
roboadhoc review+

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by nicomacr** [comment]
roboadhoc r-

**Comment by nicomacr** [comment]
roboadhoc r+

**Comment by roboadhoc** [comment]
Staging failed: ci/oba_with_tests on b4f1a4b4543925633abed1978e0543ecaca80b9b (view more at http://runbot.adhoc.com.ar/runbot/build/6335)

**Comment by nicomacr** [comment]
roboadhoc retry

**Pull request closed without merging**
